INSERT INTO country (name, capital) VALUES ('Albania','Tirana');
INSERT INTO country (name, capital) VALUES ('Algeria','Algiers');
INSERT INTO country (name, capital) VALUES ('Andorra','Andorra la Vella');
INSERT INTO country (name, capital) VALUES ('Angola','Luanda');
INSERT INTO country (name, capital) VALUES ('Argentina','Buenos Aires');
INSERT INTO country (name, capital) VALUES ('Armenia','Yerevan');
INSERT INTO country (name, capital) VALUES ('Australia','Canberra');
INSERT INTO country (name, capital) VALUES ('Austria','Vienna');
INSERT INTO country (name, capital) VALUES ('Azerbaijan','Baku');
INSERT INTO country (name, capital) VALUES ('Bahamas','Nassau');
INSERT INTO country (name, capital) VALUES ('Bahrain','Manama');
INSERT INTO country (name, capital) VALUES ('Bangladesh','Dhaka');
INSERT INTO country (name, capital) VALUES ('Barbados','Bridgetown');
INSERT INTO country (name, capital) VALUES ('Belarus','Minsk');
INSERT INTO country (name, capital) VALUES ('Belgium','Brussels');
INSERT INTO country (name, capital) VALUES ('Belize','Belmopan');
INSERT INTO country (name, capital) VALUES ('Bhutan','Thimphu');
INSERT INTO country (name, capital) VALUES ('Bolivia','La Paz');
INSERT INTO country (name, capital) VALUES ('Bosnia and Herzegovina','Sarajevo');
INSERT INTO country (name, capital) VALUES ('Botswana','Gaborone');
INSERT INTO country (name, capital) VALUES ('Brazil','Brasilia');
INSERT INTO country (name, capital) VALUES ('Brunei','Bandar Seri Begawan');
INSERT INTO country (name, capital) VALUES ('Bulgaria','Sofia');
INSERT INTO country (name, capital) VALUES ('Burkina Faso','Ouagadougou');
INSERT INTO country (name, capital) VALUES ('Burundi','Bujumbura');
INSERT INTO country (name, capital) VALUES ('Cabo Verde','Praia');
INSERT INTO country (name, capital) VALUES ('Cambodia','Phnom Penh');
INSERT INTO country (name, capital) VALUES ('Cameroon','Yaounde');
INSERT INTO country (name, capital) VALUES ('Canada','Ottawa');
INSERT INTO country (name, capital) VALUES ('Central African Republic','Bangui');
INSERT INTO country (name, capital) VALUES ('Chile','Santiago');
INSERT INTO country (name, capital) VALUES ('China','Beijing');
INSERT INTO country (name, capital) VALUES ('Colombia','Bogota');
INSERT INTO country (name, capital) VALUES ('Comoros','Moroni');
INSERT INTO country (name, capital) VALUES ('Democratic Republic of the Congo','Kinshasa');
INSERT INTO country (name, capital) VALUES ('Republic of the Congo','Brazzaville');
INSERT INTO country (name, capital) VALUES ('Costa Rica','San Jose');
INSERT INTO country (name, capital) VALUES ('Croatia','Zagreb');
INSERT INTO country (name, capital) VALUES ('Cuba','Havana');
INSERT INTO country (name, capital) VALUES ('Cyprus','Nicosia');
INSERT INTO country (name, capital) VALUES ('Czech Republic','Prague');
INSERT INTO country (name, capital) VALUES ('Denmark','Copenhagen');
INSERT INTO country (name, capital) VALUES ('Dominica','Roseau');
INSERT INTO country (name, capital) VALUES ('Dominican Republic','Santo Domingo');
INSERT INTO country (name, capital) VALUES ('Ecuador','Quito');
INSERT INTO country (name, capital) VALUES ('Egypt','Cairo');
INSERT INTO country (name, capital) VALUES ('El Salvador','San Salvador');
INSERT INTO country (name, capital) VALUES ('Equatorial Guinea','Malabo');
INSERT INTO country (name, capital) VALUES ('Eritrea','Asmara');
INSERT INTO country (name, capital) VALUES ('Estonia','Tallinn');
INSERT INTO country (name, capital) VALUES ('Ethiopia','Addis Ababa');
INSERT INTO country (name, capital) VALUES ('Fiji','Suva');
INSERT INTO country (name, capital) VALUES ('Finland','Helsinki');
INSERT INTO country (name, capital) VALUES ('France','Paris');
INSERT INTO country (name, capital) VALUES ('Gabon','Libreville');
INSERT INTO country (name, capital) VALUES ('Gambia','Banjul');
INSERT INTO country (name, capital) VALUES ('Georgia','Tbilisi');
INSERT INTO country (name, capital) VALUES ('Germany','Berlin');
INSERT INTO country (name, capital) VALUES ('Ghana','Accra');
INSERT INTO country (name, capital) VALUES ('Greece','Athens');
INSERT INTO country (name, capital) VALUES ('Guatemala','Guatemala City');
INSERT INTO country (name, capital) VALUES ('Guinea','Conakry');
INSERT INTO country (name, capital) VALUES ('Guinea-Bissau','Bissau');
INSERT INTO country (name, capital) VALUES ('Guyana','Georgetown');
INSERT INTO country (name, capital) VALUES ('Honduras','Tegucigalpa');
INSERT INTO country (name, capital) VALUES ('Hungary','Budapest');
INSERT INTO country (name, capital) VALUES ('Iceland','Reykjavik');
INSERT INTO country (name, capital) VALUES ('India','New Delhi');
INSERT INTO country (name, capital) VALUES ('Indonesia','Jakarta');
INSERT INTO country (name, capital) VALUES ('Iran','Tehran');
INSERT INTO country (name, capital) VALUES ('Iraq','Baghdad');
INSERT INTO country (name, capital) VALUES ('Ireland','Dublin');
INSERT INTO country (name, capital) VALUES ('Israel','Jerusalem');
INSERT INTO country (name, capital) VALUES ('Italy','Rome');
INSERT INTO country (name, capital) VALUES ('Jamaica','Kingston');
INSERT INTO country (name, capital) VALUES ('Japan','Tokyo');
INSERT INTO country (name, capital) VALUES ('Jordan','Amman');
INSERT INTO country (name, capital) VALUES ('Kazakhstan','Astana');
INSERT INTO country (name, capital) VALUES ('Kenya','Nairobi');
INSERT INTO country (name, capital) VALUES ('Kiribati','South Tarawa');
INSERT INTO country (name, capital) VALUES ('Kosovo','Pristina');
INSERT INTO country (name, capital) VALUES ('Kuwait','Kuwait City');
INSERT INTO country (name, capital) VALUES ('Kyrgyzstan','Bishkek');
INSERT INTO country (name, capital) VALUES ('Laos','Vientiane');
INSERT INTO country (name, capital) VALUES ('Latvia','Riga');
INSERT INTO country (name, capital) VALUES ('Lebanon','Beirut');
INSERT INTO country (name, capital) VALUES ('Lesotho','Maseru');
INSERT INTO country (name, capital) VALUES ('Liberia','Monrovia');
INSERT INTO country (name, capital) VALUES ('Libya','Tripoli');
INSERT INTO country (name, capital) VALUES ('Liechtenstein','Vaduz');
INSERT INTO country (name, capital) VALUES ('Lithuania','Vilnius');
INSERT INTO country (name, capital) VALUES ('Luxembourg','Luxembourg');
INSERT INTO country (name, capital) VALUES ('Macedonia','Skopje');
INSERT INTO country (name, capital) VALUES ('Madagascar','Antananarivo');
INSERT INTO country (name, capital) VALUES ('Malawi','Lilongwe');
INSERT INTO country (name, capital) VALUES ('Malaysia','Kuala Lumpur');
INSERT INTO country (name, capital) VALUES ('Maldives','Male');
INSERT INTO country (name, capital) VALUES ('Mali','Bamako');
INSERT INTO country (name, capital) VALUES ('Malta','Valletta');
INSERT INTO country (name, capital) VALUES ('Marshall Islands','Majuro');
INSERT INTO country (name, capital) VALUES ('Mauritania','Nouakchott');
INSERT INTO country (name, capital) VALUES ('Mauritius','Port Louis');
INSERT INTO country (name, capital) VALUES ('Mexico','Mexico City');
INSERT INTO country (name, capital) VALUES ('Micronesia','Palikir');
INSERT INTO country (name, capital) VALUES ('Moldova','Chisinau');
INSERT INTO country (name, capital) VALUES ('Monaco','Monaco');
INSERT INTO country (name, capital) VALUES ('Mongolia','Ulaanbaatar');
INSERT INTO country (name, capital) VALUES ('Montenegro','Podgorica');
INSERT INTO country (name, capital) VALUES ('Morocco','Rabat');
INSERT INTO country (name, capital) VALUES ('Mozambique','Maputo');
INSERT INTO country (name, capital) VALUES ('Namibia','Windhoek');
INSERT INTO country (name, capital) VALUES ('Nauru','Yaren District');
INSERT INTO country (name, capital) VALUES ('Nepal','Kathmandu');
INSERT INTO country (name, capital) VALUES ('Netherlands','Amsterdam');
INSERT INTO country (name, capital) VALUES ('New Zealand','Wellington');
INSERT INTO country (name, capital) VALUES ('Nicaragua','Managua');
INSERT INTO country (name, capital) VALUES ('Niger','Niamey');
INSERT INTO country (name, capital) VALUES ('Nigeria','Abuja');
INSERT INTO country (name, capital) VALUES ('North Korea','Pyongyang');
INSERT INTO country (name, capital) VALUES ('Norway','Oslo');
INSERT INTO country (name, capital) VALUES ('Oman','Muscat');
INSERT INTO country (name, capital) VALUES ('Pakistan','Islamabad');
INSERT INTO country (name, capital) VALUES ('Palau','Ngerulmud');
INSERT INTO country (name, capital) VALUES ('Palestine','Ramallah');
INSERT INTO country (name, capital) VALUES ('Panama','Panama City');
INSERT INTO country (name, capital) VALUES ('Papua New Guinea','Port Moresby');
INSERT INTO country (name, capital) VALUES ('Paraguay','Asunción');
INSERT INTO country (name, capital) VALUES ('Peru','Lima');
INSERT INTO country (name, capital) VALUES ('Philippines','Manila');
INSERT INTO country (name, capital) VALUES ('Poland','Warsaw');
INSERT INTO country (name, capital) VALUES ('Portugal','Lisbon');
INSERT INTO country (name, capital) VALUES ('Qatar','Doha');
INSERT INTO country (name, capital) VALUES ('Romania','Bucharest');
INSERT INTO country (name, capital) VALUES ('Russia','Moscow');
INSERT INTO country (name, capital) VALUES ('Rwanda','Kigali');
INSERT INTO country (name, capital) VALUES ('Saint Kitts and Nevis','Basseterre');
INSERT INTO country (name, capital) VALUES ('Saint Lucia','Castries');
INSERT INTO country (name, capital) VALUES ('Saint Vincent and the Grenadines','Kingstown');
INSERT INTO country (name, capital) VALUES ('Samoa','Apia');
INSERT INTO country (name, capital) VALUES ('San Marino','San Marino');
INSERT INTO country (name, capital) VALUES ('Saudi Arabia','Riyadh');
INSERT INTO country (name, capital) VALUES ('Senegal','Dakar');
INSERT INTO country (name, capital) VALUES ('Serbia','Belgrade');
INSERT INTO country (name, capital) VALUES ('Seychelles','Victoria');
INSERT INTO country (name, capital) VALUES ('Sierra Leone','Freetown');
INSERT INTO country (name, capital) VALUES ('Singapore','Singapore');
INSERT INTO country (name, capital) VALUES ('Slovakia','Bratislava');
INSERT INTO country (name, capital) VALUES ('Slovenia','Ljubljana');
INSERT INTO country (name, capital) VALUES ('Solomon Islands','Honiara');
INSERT INTO country (name, capital) VALUES ('Somalia','Mogadishu');
INSERT INTO country (name, capital) VALUES ('South Africa','Pretoria');
INSERT INTO country (name, capital) VALUES ('South Korea','Seoul');
INSERT INTO country (name, capital) VALUES ('South Sudan','Juba');
INSERT INTO country (name, capital) VALUES ('Spain','Madrid');
INSERT INTO country (name, capital) VALUES ('Sudan','Khartoum');
INSERT INTO country (name, capital) VALUES ('Suriname','Paramaribo');
INSERT INTO country (name, capital) VALUES ('Swaziland','Mbabane');
INSERT INTO country (name, capital) VALUES ('Sweden','Stockholm');
INSERT INTO country (name, capital) VALUES ('Switzerland','Bern');
INSERT INTO country (name, capital) VALUES ('Syria','Damascus');
INSERT INTO country (name, capital) VALUES ('Taiwan','Taipei');
INSERT INTO country (name, capital) VALUES ('Tajikistan','Dushanbe');
INSERT INTO country (name, capital) VALUES ('Tanzania','Dodoma');
INSERT INTO country (name, capital) VALUES ('Thailand','Bangkok');
INSERT INTO country (name, capital) VALUES ('Togo','Lome');
INSERT INTO country (name, capital) VALUES ('Trinidad and Tobago','Port of Spain');
INSERT INTO country (name, capital) VALUES ('Tunisia','Tunis');
INSERT INTO country (name, capital) VALUES ('Turkey','Ankara');
INSERT INTO country (name, capital) VALUES ('Turkmenistan','Ashgabat');
INSERT INTO country (name, capital) VALUES ('Tuvalu','Funafuti');
INSERT INTO country (name, capital) VALUES ('Uganda','Kampala');
INSERT INTO country (name, capital) VALUES ('Ukraine','Kyiv');
INSERT INTO country (name, capital) VALUES ('United Arab Emirates','Abu Dhabi');
INSERT INTO country (name, capital) VALUES ('United Kingdom','London');
INSERT INTO country (name, capital) VALUES ('United States of America','Washington');
INSERT INTO country (name, capital) VALUES ('Uruguay','Montevideo');
INSERT INTO country (name, capital) VALUES ('Uzbekistan','Tashkent');
INSERT INTO country (name, capital) VALUES ('Vanuatu','Port Vila');
INSERT INTO country (name, capital) VALUES ('Venezuela','Caracas');
INSERT INTO country (name, capital) VALUES ('Vietnam','Hanoi');
INSERT INTO country (name, capital) VALUES ('Zambia','Lusaka');
INSERT INTO country (name, capital) VALUES ('Zimbabwe','Harare');
